create table if not exists settlements (
  show_id bigint not null references shows (id) unique,
  deal_type text not null default 'straight_split',
  deal_threshold numeric(10,2) default 0,
  artist_split_pct numeric(5,2) not null default 75,
  income_square numeric(10,2) default 0,
  income_venmo numeric(10,2) default 0,
  income_cash numeric(10,2) default 0,
  exp_square_fees numeric(10,2) default 0,
  exp_venmo_fees numeric(10,2) default 0,
  exp_sound_engineer numeric(10,2) default 0,
  exp_photos numeric(10,2) default 0,
  exp_door_person numeric(10,2) default 0,
  exp_ad_print numeric(10,2) default 0,
  exp_ad_online numeric(10,2) default 0,
  exp_snacks numeric(10,2) default 0,
  exp_beer numeric(10,2) default 0,
  beverage_income_venmo numeric(10,2) default 0,
  beverage_income_cash numeric(10,2) default 0,
  extra_line_items jsonb not null default '[]',
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint settlements_deal_type_check check (deal_type in ('straight_split', 'venue_guarantee_then_split'))
);
